apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: ck-postgres
  namespace: codekarma

spec:
  enableLogicalBackup: true
  teamId: flipkart
  numberOfInstances: 2
  imagePullSecrets:
    - name: ckn-ghcr-secret
  serviceAccountName: postgres-pod
  postgresql:
    version: "15"

  volume:
    size: 10Gi
    storageClass: ckn-gcp-sc

  users:
    cknexus:
      - superuser
      - createdb
  env:
    - name: WAL_GS_BUCKET
      value: "ck-flipkart-pg-storage-bucket/prod/"
  databases:
    ckservicedb: cknexus


