---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-postgres
  namespace: codekarma
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:16.2

  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: standard

  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: postgres-secret

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  monitoring:
    enablePodMonitor: false

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: codekarma
type: kubernetes.io/basic-auth
stringData:
  username: cknexus
  password: cknexus
