apiVersion: v1
kind: ServiceAccount
metadata:
  name: ck-postgres
  namespace: codekarma
  annotations:
    iam.gke.io/gcp-service-account: codekarma-dev-node-sa@ck-flipkart-pg.iam.gserviceaccount.com
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ck-postgres-standby
  namespace: codekarma
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:16.2

  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: codekarma-dev-node-sa@ck-flipkart-pg.iam.gserviceaccount.com
    spec:
      serviceAccountName: ck-postgres

  storage:
    size: 20Gi
    storageClass: standard

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  monitoring:
    enablePodMonitor: false

  # 🔥 THIS IS THE KEY PART 🔥
  bootstrap:
    recovery:
      source: primary-cluster

  externalClusters:
    - name: primary-cluster
      barmanObjectStore:
        destinationPath: "gs://ck-flipkart-pg-storage-bucket/codekarma/ck-postgres"
        googleCredentials:
          gkeEnvironment: true
