apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: ck-postgres
  namespace: codekarma

spec:
  enableLogicalBackup: true
  teamId: flipkart
  numberOfInstances: 2

  # additionalVolumes:
  #   - name: sql-scripts-volume
  #     mountPath: /scripts
  #     targetContainers:
  #       - init-sql
  #     volumeSource:
  #       configMap:
  #         name: ck-postgres-init-sql
  # # initContainers:
  #   - name: init-sql-script
  #     image: "postgres:15"
  #     env:
  #       - name: PGPASSWORD
  #         valueFrom:
  #           secretKeyRef:
  #             name: cknexus.ck-postgres.credentials.postgresql.acid.zalan.do
  #             key: password
  #     volumeMounts:
  #       - name: sql-scripts-volume
  #         mountPath: /scripts
      # command: 
      #   - /bin/sh
      #   - -c
      #   - |
      #     until pg_isready -h ck-postgres -U cknexus; do
      #       echo "Waiting for postgres..."
      #       sleep 2
      #     done
      #     # Match the filename in your ConfigMap
      #     psql -h ck-postgres -U cknexus -d ckservicedb -f /scripts/01-init.sql
  serviceAccountName: postgres-pod
  postgresql:
    version: "15"

  volume:
    size: 10Gi
    storageClass: ckn-gcp-sc

  users:
    cknexus:
      - superuser
      - createdb
  env:
    - name: WAL_GS_BUCKET
      value: "ck-flipkart-pg-storage-bucket/prod/"
  databases:
    ckservicedb: cknexus

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-pod
  namespace: codekarma
  annotations:
    iam.gke.io/gcp-service-account: codekarma-dev-node-sa@ck-flipkart-pg.iam.gserviceaccount.com


