---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-walg
  namespace: codekarma
  annotations:
    iam.gke.io/gcp-service-account: codekarma-dev-node-sa@ck-flipkart-pg.iam.gserviceaccount.com
---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-walg-backup
  namespace: codekarma
spec:
  schedule: "*/1 * * * *"   # Every day at 02:00
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: postgres-walg
          restartPolicy: OnFailure
          containers:
            - name: wal-g-backup
              image: ghcr.io/zalando/spilo-16:3.3-p1
              command:
                - /bin/bash
                - -c
                - |
                  wal-g backup-push /home/postgres/pgdata
              env:
                - name: USE_WALG_BACKUP
                  value: "true"
                - name: WAL_GS_BUCKET
                  value: "gs://ck-flipkart-pg-storage-bucket"

---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: ck-postgres
  namespace: codekarma
spec:
  teamId: flipkart

  numberOfInstances: 3

  postgresql:
    version: "15"

  volume:
    size: 10Gi
    storageClass: ckn-gcp-sc

  users:
    cknexus:
      - superuser
      - createdb

  databases:
    ckservicedb: cknexus
  
  env:
    - name: USE_WALG_BACKUP
      value: "true"

    - name: WAL_GS_BUCKET
      value: "gs://ck-flipkart-pg-storage-bucket"