---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-walg
  namespace: codekarma
  annotations:
    iam.gke.io/gcp-service-account: codekarma-dev-node-sa@ck-flipkart-pg.iam.gserviceaccount.com
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: ck-postgres
  namespace: codekarma
spec:
  teamId: flipkart

  numberOfInstances: 3

  postgresql:
    version: "15"

  volume:
    size: 10Gi
    storageClass: ckn-gcp-sc

  users:
    cknexus:
      - superuser
      - createdb

  databases:
    ckservicedb: cknexus
    env:
    - name: USE_WALG_BACKUP
      value: "true"

    - name: WAL_GS_BUCKET
      value: "ck-flipkart-pg-storage-bucket"