apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: ck-postgres
  namespace: codekarma

spec:
  enableLogicalBackup: true
  teamId: flipkart
  numberOfInstances: 2

  serviceAccountName: postgres-backup   

  postgresql:
    version: "15"

  volume:
    size: 10Gi
    storageClass: ckn-gcp-sc

  users:
    cknexus:
      - superuser
      - createdb

  databases:
    ckservicedb: cknexus
