apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup
  namespace: database
  annotations:
    iam.gke.io/gcp-service-account: codekarma-dev-node-sa@ck-flipkart-pg.iam.gserviceaccount.com
