apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flipkart-platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/firgga-sunil/ck-flipkart-helm-charts.git"
    targetRevision: main
    path: applications/flipkart
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
